# Generated by joshaven.com on Tue 08 Sep 2026 06:25:01 AM CDT
/ip firewall address-list
add list=blacklist_DSHIELD address=45.33.41.0/24 comment=DShield
add list=blacklist_DSHIELD address=16.5.0.0/24 comment=DShield
add list=blacklist_DSHIELD address=69.5.169.0/24 comment=DShield
add list=blacklist_DSHIELD address=66.132.186.0/24 comment=DShield
add list=blacklist_DSHIELD address=185.242.226.0/24 comment=DShield
add list=blacklist_DSHIELD address=85.217.149.0/24 comment=DShield
add list=blacklist_DSHIELD address=64.62.197.0/24 comment=DShield
add list=blacklist_DSHIELD address=85.217.140.0/24 comment=DShield
add list=blacklist_DSHIELD address=193.163.125.0/24 comment=DShield
add list=blacklist_DSHIELD address=147.185.132.0/24 comment=DShield
add list=blacklist_DSHIELD address=198.235.24.0/24 comment=DShield
add list=blacklist_DSHIELD address=77.239.124.0/24 comment=DShield
add list=blacklist_DSHIELD address=205.210.31.0/24 comment=DShield
add list=blacklist_DSHIELD address=66.132.172.0/24 comment=DShield
add list=blacklist_DSHIELD address=45.205.1.0/24 comment=DShield
add list=blacklist_DSHIELD address=77.90.185.0/24 comment=DShield
add list=blacklist_DSHIELD address=66.132.195.0/24 comment=DShield
add list=blacklist_DSHIELD address=213.209.159.0/24 comment=DShield
add list=blacklist_DSHIELD address=45.156.128.0/24 comment=DShield
add list=blacklist_DSHIELD address=45.194.67.0/24 comment=DShield
