# Generated by joshaven.com on Fri 31 Jul 2026 06:25:01 AM CDT
/ip firewall address-list
add list=blacklist_DSHIELD address=69.5.169.0/24 comment=DShield
add list=blacklist_DSHIELD address=66.132.186.0/24 comment=DShield
add list=blacklist_DSHIELD address=64.62.197.0/24 comment=DShield
add list=blacklist_DSHIELD address=45.194.67.0/24 comment=DShield
add list=blacklist_DSHIELD address=66.132.195.0/24 comment=DShield
add list=blacklist_DSHIELD address=194.88.98.0/24 comment=DShield
add list=blacklist_DSHIELD address=156.225.1.0/24 comment=DShield
add list=blacklist_DSHIELD address=162.217.100.0/24 comment=DShield
add list=blacklist_DSHIELD address=65.49.1.0/24 comment=DShield
add list=blacklist_DSHIELD address=91.92.40.0/24 comment=DShield
add list=blacklist_DSHIELD address=167.94.145.0/24 comment=DShield
add list=blacklist_DSHIELD address=45.198.224.0/24 comment=DShield
add list=blacklist_DSHIELD address=45.205.1.0/24 comment=DShield
add list=blacklist_DSHIELD address=193.163.125.0/24 comment=DShield
add list=blacklist_DSHIELD address=66.132.172.0/24 comment=DShield
add list=blacklist_DSHIELD address=213.209.159.0/24 comment=DShield
add list=blacklist_DSHIELD address=91.231.89.0/24 comment=DShield
add list=blacklist_DSHIELD address=151.243.11.0/24 comment=DShield
add list=blacklist_DSHIELD address=193.24.211.0/24 comment=DShield
add list=blacklist_DSHIELD address=160.119.76.0/24 comment=DShield
