# Generated by joshaven.com on Tue 09 Sep 2025 06:25:01 AM CDT
/ip firewall address-list
add list=blacklist_DSHIELD address=123.136.6.0/24 comment=DShield
add list=blacklist_DSHIELD address=64.62.156.0/24 comment=DShield
add list=blacklist_DSHIELD address=193.163.125.0/24 comment=DShield
add list=blacklist_DSHIELD address=71.6.232.0/24 comment=DShield
add list=blacklist_DSHIELD address=167.94.145.0/24 comment=DShield
add list=blacklist_DSHIELD address=79.124.49.0/24 comment=DShield
add list=blacklist_DSHIELD address=206.168.34.0/24 comment=DShield
add list=blacklist_DSHIELD address=167.94.138.0/24 comment=DShield
add list=blacklist_DSHIELD address=207.90.244.0/24 comment=DShield
add list=blacklist_DSHIELD address=198.235.24.0/24 comment=DShield
add list=blacklist_DSHIELD address=65.49.1.0/24 comment=DShield
add list=blacklist_DSHIELD address=205.210.31.0/24 comment=DShield
add list=blacklist_DSHIELD address=216.180.246.0/24 comment=DShield
add list=blacklist_DSHIELD address=91.196.152.0/24 comment=DShield
add list=blacklist_DSHIELD address=176.65.148.0/24 comment=DShield
add list=blacklist_DSHIELD address=147.185.132.0/24 comment=DShield
add list=blacklist_DSHIELD address=64.62.197.0/24 comment=DShield
add list=blacklist_DSHIELD address=80.75.212.0/24 comment=DShield
add list=blacklist_DSHIELD address=79.124.58.0/24 comment=DShield
add list=blacklist_DSHIELD address=176.65.149.0/24 comment=DShield
