name: Update dshield.rsc

on:
  schedule:
    - cron: "10 1 */2 * *"  # Corre cada dos dias
  workflow_dispatch:  # Permite ejecutarlo manualmente

jobs:
  update-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Download and Modify File
        run: |
          curl -o dshield.rsc https://joshaven.com/dshield.rsc
          sed 's/blacklist/blacklist_DSHIELD/g' dshield.rsc > DSHIELD_modified.rsc

      - name: Commit and Push Changes
        env:
          PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.email "bot@example.com"
          git config --global user.name "GitHub Bot"
          git add DSHIELD_modified.rsc
          git commit -m "Updated modified dshield.rsc" || echo "No changes to commit"
          git push https://x-access-token:${PAT}@github.com/EdwardChCriollo/Blacklist-Automation-JACENET.git main
