name: Update CINSscore.rsc

on:
  schedule:
    - cron: "5 1 * * *"  # Corre cada dos dias
  workflow_dispatch:  # Permite ejecutarlo manualmente

jobs:
  update-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Download and Modify File
        run: |
          curl -o CINSscore.rsc https://joshaven.com/CINSscore.rsc
          sed 's/blacklist/blacklist_CINS/g' CINSscore.rsc > CINSscore_modified.rsc

      - name: Commit and Push Changes
        env:
          PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.email "bot@example.com"
          git config --global user.name "GitHub Bot"
          git add CINSscore_modified.rsc
          git commit -m "Updated modified CINSscore.rsc" || echo "No changes to commit"
          git push https://x-access-token:${PAT}@github.com/EdwardChCriollo/Blacklist-Automation-JACENET.git main
